ARG ORACLE_LINUX_IMAGE=container-registry.oracle.com/os/oraclelinux:9-slim

FROM ${ORACLE_LINUX_IMAGE}

ARG NODEJS_STREAM=22
ARG NODEJS_MIN_VERSION=22.23.0

RUN microdnf update -y \
    && microdnf install -y dnf shadow-utils \
    && dnf --refresh -y upgrade \
    && dnf -y module reset nodejs \
    && dnf -y module enable nodejs:${NODEJS_STREAM} \
    && dnf --refresh -y install nodejs npm \
    && dnf --refresh -y upgrade \
    && dnf clean all \
    && microdnf clean all \
    && rm -rf /var/cache/dnf /var/cache/yum

RUN groupadd --gid 10001 node \
    && useradd --uid 10001 --gid 10001 --home-dir /tmp --no-create-home --shell /sbin/nologin node \
    && node -e 'const current=process.versions.node.split(".").map(Number); const minimum=process.argv[1].split(".").map(Number); for (let i=0; i<3; i+=1) { if ((current[i] || 0) > (minimum[i] || 0)) process.exit(0); if ((current[i] || 0) < (minimum[i] || 0)) { console.error(`Node.js ${process.versions.node} is below required ${process.argv[1]}`); process.exit(1); } }' "${NODEJS_MIN_VERSION}" \
    && node --version \
    && npm --version

ENV HOME=/tmp
